---
- name: ensure PlayOnLinux key is present 
  apt_key:
    url: http://deb.playonlinux.com/public.gpg
    state: present 

- name: ensure PlayOnLinux repository is enabled
  apt_repository:
    repo: deb http://deb.playonlinux.com/ trusty main
    update_cache: yes
    state: present

- name: ensure playonlinux is installed
  apt: 
    pkg: "{{ item }}" 
    state: latest 
    update_cache: yes 
    cache_valid_time: 600
  with_items:
    - playonlinux
