---
- name: ensure i3wm dependencies are installed
  apt: 
    pkg: "{{ item }}" 
    state: latest 
    update_cache: yes 
    cache_valid_time: 600
  with_items:
    - python-software-properties

- name: ensure PlayOnLinux repository is enabled
  apt_repository:
    repo: deb http://debian.sur5r.net/i3/ {{ ansible_distribution_release }} universe
    update_cache: yes
    state: present

- name: ensure i3wm key is present 
  apt: 
    pkg: sur5r-keyring
    state: latest 
    update_cache: yes 
    force: yes 

- name: ensure i3wm is installed
  apt: 
    pkg: "{{ item }}" 
    state: latest 
    update_cache: yes 
  with_items:
    - blueman
    - conky-all
    - dmenu
    - dunst
    - dzen2
    - i3
    - i3status
    - suckless-tools
    - unclutter
    - rxvt-unicode-256color
    - xautolock
    - xbacklight
    - xclip

- name: update custom desktop configuration from template
  template:
    src: usr/share/xsessions/custom.desktop
    dest: /usr/share/xsessions/custom.desktop
    owner: root
    group: root
    mode: 0644
